### ISSUE TITLE
Range queries fail on Windows 7

### ISSUE THREAD

**Issue by GoogleCodeExporter** [byzhang/terrastore#116]
```
Terrastore Server 0.7.2-SNAPSHOT - 22:14:02.018 - java.io.IOException: The 
filename, directory name, or volume label syntax is incorrect
terrastore.communication.ProcessingException: java.io.IOException: The 
filename, directory name, or volume label syntax is incorrect
        at terrastore.communication.remote.RemoteNode.send(RemoteNode.java:145) [terrastore-0.7.2-SNAPSHOT.jar:na]
        at terrastore.service.impl.DefaultQueryService$13.map(DefaultQueryService.java:417) [terrastore-0.7.2-SNAPSHOT.jar:na]
        at terrastore.service.impl.DefaultQueryService$13.map(DefaultQueryService.java:1) [terrastore-0.7.2-SNAPSHOT.jar:na]
        at terrastore.util.collect.parallel.ParallelUtils$1.call(ParallelUtils.java:51) [terrastore-0.7.2-SNAPSHOT.jar:na]
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [na:1.6.0_15]
        at java.util.concurrent.FutureTask.run(FutureTask.java:138) [na:1.6.0_15]
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [na:1.6.0_15]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [na:1.6.0_15]
        at java.lang.Thread.run(Thread.java:619) [na:1.6.0_15]
```

Original issue reported on code.google.com by `johansso...@gmail.com` on 20 Oct 2010 at 8:18

**Comment by GoogleCodeExporter** [comment]
```
What mapper and reducer functions were you executing?
Did you see any other exception in logs?
```

Original comment by `sergio.b...@gmail.com` on 20 Oct 2010 at 8:32

**Comment by GoogleCodeExporter** [comment]
```
I'm using size/size.
No other exceptions.

The query still returns a {"size":0} document.
```

Original comment by `johansso...@gmail.com` on 20 Oct 2010 at 8:37

**Comment by GoogleCodeExporter** [comment]
```
And how are keys composed? An example of the queried range?
```

Original comment by `sergio.b...@gmail.com` on 20 Oct 2010 at 9:00

**Comment by GoogleCodeExporter** [comment]
```
Oh, I think the problem is the snapshot file saved and accessed on disk, hence 
the IOException: take a loot at the SortedSnapshot class.

If so, you should get the same exception with simple range queries too: is that 
the case?
```

Original comment by `sergio.b...@gmail.com` on 21 Oct 2010 at 6:07

**Comment by GoogleCodeExporter** [comment]
```
That is very likely to be it - the range queries behave in the exact same way.
```

Original comment by `johansso...@gmail.com` on 21 Oct 2010 at 7:28
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `sergio.b...@gmail.com` on 21 Oct 2010 at 8:38
- Changed title: **Range queries fail on Win7**

**Comment by GoogleCodeExporter** [comment]
Original comment by `sergio.b...@gmail.com` on 21 Oct 2010 at 8:39
- Changed title: **Range queries fail on Windows 7**
- Changed state: **Started**
- Added labels: **Milestone-0.8.0**

**Comment by GoogleCodeExporter** [comment]
```
The snapshot files were indeed the problem.

Previously named <bucket>:<comparator>, which doesn't work on Win systems.
Renamed it to <bucket>-<comparator>.

Although it seems kind of obvious that it will work universally now, it should 
be verified on *nix/MacOS.
```

Original comment by `johansso...@gmail.com` on 21 Oct 2010 at 8:57
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Works here on my Mac.
Good catch!
```

Original comment by `sergio.b...@gmail.com` on 22 Oct 2010 at 9:24
