### ISSUE TITLE
Exceptions when querying/processing json array documents

### ISSUE THREAD

**Issue by GoogleCodeExporter** [byzhang/terrastore#119]
```
I've put an json array value into terrastore, 
after I did a search with map reduce and I've got this exception:

Terrastore - java.lang.IllegalStateException: Value should have been already 
validated!
[INFO] [node-1] terrastore.store.StoreOperationException: 
java.lang.IllegalStateException: Value should have been already validated!
[INFO] [node-1]     at terrastore.store.impl.TCBucket.map(TCBucket.java:235) 
[classes/:na]
[INFO] [node-1]     at terrastore.store.impl.TCStore.map(TCStore.java:182) 
[classes/:na]
[INFO] [node-1]     at 
terrastore.communication.protocol.MapCommand.executeOn(MapCommand.java:67) 
[classes/:na]
[INFO] [node-1]     at 
terrastore.communication.protocol.MapCommand.executeOn(MapCommand.java:35) 
[classes/:na]
[INFO] [node-1]     at 
terrastore.communication.process.StoreHandler.handle(StoreHandler.java:34) 
[classes/:na]

```

Original issue reported on code.google.com by `you...@gmail.com` on 22 Oct 2010 at 12:11
- Blocked on: #130

**Comment by GoogleCodeExporter** [comment]
```
Changed the issue title because the exception is fired for every query/update 
operation involving a json document made up of a single json array.
```

Original comment by `sergio.b...@gmail.com` on 22 Oct 2010 at 12:21
- Changed title: **Exceptions when querying/processing json array documents**
- Changed state: **Accepted**
- Added labels: **Type-Defect**, **Priority-High**, **Project-Terrastore**, **Milestone-0.8.0**

**Comment by GoogleCodeExporter** [comment]
Original comment by `sergio.b...@gmail.com` on 1 Nov 2010 at 11:34

**Comment by GoogleCodeExporter** [comment]
```
Fixed as of issue 130.
```

Original comment by `sergio.b...@gmail.com` on 1 Nov 2010 at 11:35
- Changed state: **Fixed**
