### ISSUE TITLE
Java Heap Error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [byzhang/terrastore#179]
```
Hi

I have a ensemble of 6 clusters running. When I do a range query on it, I ama 
getting a 'Java Heap Error'. Any idea why this is happening? 
```

Original issue reported on code.google.com by `rohi...@gmail.com` on 1 Aug 2011 at 10:40

**Comment by GoogleCodeExporter** [comment]
```
15:30:35.843Server9540 - pool-12-thread-42 - 
terrastore.communication.process.AbstractProcessor - Java heap space
terrastore.communication.ProcessingException: Java heap space
        at terrastore.communication.process.AbstractProcessor.process(AbstractProcessor.java:80) ~[terrastore-0.8.2-SNAPSHOT.jar:na]
        at terrastore.communication.local.LocalProcessor.process(LocalProcessor.java:47) ~[terrastore-0.8.2-SNAPSHOT.jar:na]
        at terrastore.communication.local.LocalNode.send(LocalNode.java:52) ~[terrastore-0.8.2-SNAPSHOT.jar:na]
        at terrastore.communication.protocol.GetValuesCommand.executeOn(GetValuesCommand.java:81) ~[terrastore-0.8.2-SNAPSHOT.jar:na]
        at terrastore.communication.process.RouterHandler.handle(RouterHandler.java:35) ~[terrastore-0.8.2-SNAPSHOT.jar:na]
        at terrastore.communication.process.AbstractProcessor$AsyncCallable.call(AbstractProcessor.java:129) ~[terrastore-0.8.2-SNAPSHOT.jar:na]
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [na:1.6.0_26]
        at java.util.concurrent.FutureTask.run(FutureTask.java:138) [na:1.6.0_26]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441) [na:1.6.0_26]
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [na:1.6.0_26]
        at java.util.concurrent.FutureTask.run(FutureTask.java:138) [na:1.6.0_26]
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [na:1.6.0_26]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [na:1.6.0_26]
        at java.lang.Thread.run(Thread.java:662) [na:1.6.0_26]

```

Original comment by `rohi...@gmail.com` on 2 Aug 2011 at 3:36

**Comment by GoogleCodeExporter** [comment]
```
Range queries materialize lots of keys on the server node you handed the 
request to, so they were probably too much for the configured memory, or your 
values in range were too much/too big: how many entries you have?  How big are 
they? How much memory you have configured?
```

Original comment by `sergio.b...@gmail.com` on 2 Aug 2011 at 3:42

**Comment by GoogleCodeExporter** [comment]
```
Unable to investigate more with such a few details.
```

Original comment by `sergio.b...@gmail.com` on 2 Sep 2011 at 9:06
- Changed state: **Invalid**
