### ISSUE TITLE
NPE in RemoteNode timeout handling.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [byzhang/terrastore#182]
```
java.lang.NullPointerException: null
        at terrastore.communication.remote.RemoteNode$ClientHandler.signalCommandResponse(RemoteNode.java:244) ~[terrastore-0.8.2-SNAPSHOT.jar:na]
        at terrastore.communication.remote.RemoteNode$ClientHandler.messageReceived(RemoteNode.java:228) ~[terrastore-0.8.2-SNAPSHOT.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302) ~[netty-3.2.3.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:317) ~[netty-3.2.3.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:299) ~[netty-3.2.3.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:216) ~[netty-3.2.3.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274) ~[netty-3.2.3.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261) ~[netty-3.2.3.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:350) ~[netty-3.2.3.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281) ~[netty-3.2.3.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201) ~[netty-3.2.3.Final.jar:na]
        at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46) [netty-3.2.3.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [na:1.6.0_26]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [na:1.6.0_26]
        at java.lang.Thread.run(Thread.java:662) [na:1.6.0_26]
```

Original issue reported on code.google.com by `sergio.b...@gmail.com` on 2 Aug 2011 at 4:03

**Comment by GoogleCodeExporter** [comment]
Original comment by `sergio.b...@gmail.com` on 2 Aug 2011 at 4:04
- Changed state: **Fixed**
