### ISSUE TITLE
Cygwin problem in startup scripts

### ISSUE THREAD

**Issue by GoogleCodeExporter** [byzhang/terrastore#23]
```
Environment:
- Windows XP
- cygwin
- java (jre) 1.6.0_17
- terrastore version 0.3

I performed the following steps (all in cygwin window):
- install terrastore (followed ' Single-master Terrastore cluster 
installation');
- start the master
- start the server

The server response with:

mawi@pc583 /cygdrive/d/java/terrastore/server/bin
$ java -version
java version "1.6.0_17"
Java(TM) SE Runtime Environment (build 1.6.0_17-b04)
Java HotSpot(TM) Client VM (build 14.3-b01, mixed mode, sharing)

mawi@pc583 /cygdrive/d/java/terrastore/server/bin
$ sh ./start.sh --master localhost:9510
cygpath: cannot create short name of localhost9510
Starting BootJarTool...
2010-01-02 13:11:20,714 INFO - Terracotta 3.1.1, as of 20091009-141004 
(Revision 13788 by cruise@su10mo5 from 3.1)
2010-01-02 13:11:21,230 INFO - Configuration loaded from the Java resource 
at '/com/tc/config/schema/setup/default-config.xml', rela
tive to class 
com.tc.config.schema.setup.StandardXMLFileConfigurationCreator.
2010-01-02 13:11:22,027 INFO - Found boot JAR file at 
'D:\java\terrastore\server\terrastore-master-libs\lib\dso-boot\dso-boot-
hotspo
t_win32_160_13.jar'; validating...
2010-01-02 13:11:22,324 INFO - Valid.
Error occurred during initialization of VM
java.lang.NoSuchMethodError: 
java.lang.Integer.getAndRemoveCacheProperties()V
        at java.lang.System.initializeSystemClass(Unknown Source)
```

Original issue reported on code.google.com by `mark.wig...@gmail.com` on 2 Jan 2010 at 12:20

**Comment by GoogleCodeExporter** [comment]
```
Hi Mark, 

it seems it's unable to load the configuration from the master server at
localhost:9510, probably related to some incompatibility with the startup 
script and
cygwin.

May you try it on a "real" unix system?

If not, please give a try to the attached script, copying it in server/bin and
running as:
$> sh start_modified.sh

Let me know.
Cheers,

Sergio B.
```

Original comment by `sergio.b...@gmail.com` on 2 Jan 2010 at 12:51
- Changed title: **Cygwin problem: server at startup: NoSuchMethodError: java.lang.Integer.getAndRemoveCacheProperties()**
- Added labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
Here's the modified startup script.
```

Original comment by `sergio.b...@gmail.com` on 2 Jan 2010 at 12:54

Attachments:
- [start-modified.sh](https://storage.googleapis.com/google-code-attachments/terrastore/issue-23/comment-2/start-modified.sh)

**Comment by GoogleCodeExporter** [comment]
```
As a side note, what cygwin version are you using?
```

Original comment by `sergio.b...@gmail.com` on 2 Jan 2010 at 1:03

**Comment by GoogleCodeExporter** [comment]
```
I use the lastest cygwin (2.674) and reinstalled it completely, just be sure.
On cygqin I don't see a difference with the new script. I will retry on a 
unbuntu
system and see what happens.
```

Original comment by `mark.wig...@gmail.com` on 2 Jan 2010 at 1:08

**Comment by GoogleCodeExporter** [comment]
```
The cygwin version number of of the installer (setup.exe), cygwin itself is 
1.7.1-1
```

Original comment by `mark.wig...@gmail.com` on 2 Jan 2010 at 1:13

**Comment by GoogleCodeExporter** [comment]
```
The first analysis on my cygwin environment is:
- I have java JDK 1.6.0-13
- I have a java JRE 1.6.0_17

The file
'D:\java\terrastore\server\terrastore-master-libs\lib\dso-boot\dso-boot-hotspot_
win32_160_13.jar
seems to be generated for the JDK version.

I changed the java via an JAVA variable and adding quote's around the 
classpath. Then
I got errors like this (I attached the modified start.sh I used)

Exception in thread "main" java.lang.NoClassDefFoundError: 
terrastore/startup/Startup
Caused by: java.lang.ClassNotFoundException: terrastore.startup.Startup
        at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
        at sun.misc.Launcher$AppClassLoader.findClass(Launcher.java)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
        at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
Could not find the main class: terrastore.startup.Startup.  Program will exit.

Next try is to use a JDK in sync with a JRE version, maybe that helps.
```

Original comment by `mark.wig...@gmail.com` on 2 Jan 2010 at 1:53

Attachments:
- [start.sh](https://storage.googleapis.com/google-code-attachments/terrastore/issue-23/comment-6/start.sh)

**Comment by GoogleCodeExporter** [comment]
```
Great, thanks for your effort: I don't have a cygwin installation to test the 
script
at the moment, so you're helping a lot.

It may be a problem with the classpath env variable, please modify the script 
and try
the trick explained here:
http://mike.hostetlerhome.com/2009/09/01/getting-cygwin-and-java-to-play-togethe
r/
```

Original comment by `sergio.b...@gmail.com` on 2 Jan 2010 at 2:00

**Comment by GoogleCodeExporter** [comment]
```
You may have to fix the TERRASTORE_HOME path as well.
```

Original comment by `sergio.b...@gmail.com` on 2 Jan 2010 at 2:02

**Comment by GoogleCodeExporter** [comment]
```
Still, the "cygpath: cannot create short name of localhost9510" message bugs 
me ...
It seems it's interpreting the host:port like a file name ...
```

Original comment by `sergio.b...@gmail.com` on 2 Jan 2010 at 2:30

**Comment by GoogleCodeExporter** [comment]
```
I changed the script, and now I got. What could be the problem?

$ ./start.sh --master localhost:9510
cygpath: cannot create short name of localhost9510
Starting BootJarTool...
2010-01-02 15:37:36,069 INFO - Terracotta 3.1.1, as of 20091009-141004 (Revision
13788 by cruise@su10mo5 from 3.1)
2010-01-02 15:37:36,616 INFO - Configuration loaded from the Java resource at
'/com/tc/config/schema/setup/default-config.xml', rela
tive to class com.tc.config.schema.setup.StandardXMLFileConfigurationCreator.
2010-01-02 15:37:37,397 INFO - Found boot JAR file at
'D:\java\terrastore\server\terrastore-master-libs\lib\dso-boot\dso-boot-hotspo
t_win32_160_13.jar'; validating...
2010-01-02 15:37:37,709 INFO - Valid.
2010-01-02 15:37:39,038 INFO - Terracotta 3.1.1, as of 20091009-141004 (Revision
13788 by cruise@su10mo5 from 3.1)
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at
com.tc.object.bytecode.hook.impl.ClassProcessorHelper.createGlobalContext(ClassP
rocessorHelper.java:494)
        at
com.tc.object.bytecode.hook.impl.ClassProcessorHelper.initialize(ClassProcessorH
elper.java:349)
        at
com.tc.object.bytecode.hook.impl.ClassProcessorHelper.defineClass0Pre(ClassProce
ssorHelper.java:533)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:56)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
        at sun.misc.Launcher$AppClassLoader.findClass(Launcher.java)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
        at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
Caused by: com.tc.config.schema.setup.ConfigurationSetupException:
*******************************************************************************
You must specify the location of the Terracotta configuration file for this 
process,
using the 'tc.config' system property.
*******************************************************************************

        at
com.tc.config.schema.setup.StandardTVSConfigurationSetupManagerFactory.<init>(St
andardTVSConfigurationSetupManagerFactory
.java:113)
        at
com.tc.config.schema.setup.StandardTVSConfigurationSetupManagerFactory.<init>(St
andardTVSConfigurationSetupManagerFactory
.java:59)
        at
com.tc.config.schema.setup.StandardTVSConfigurationSetupManagerFactory.<init>(St
andardTVSConfigurationSetupManagerFactory
.java:53)
        at
com.tc.config.schema.setup.StandardTVSConfigurationSetupManagerFactory.<init>(St
andardTVSConfigurationSetupManagerFactory
.java:47)
        at
com.tc.object.bytecode.hook.impl.DSOContextImpl.getGlobalConfigHelper(DSOContext
Impl.java:235)
        at
com.tc.object.bytecode.hook.impl.DSOContextImpl.createGlobalContext(DSOContextIm
pl.java:85)
        ... 19 more
```

Original comment by `mark.wig...@gmail.com` on 2 Jan 2010 at 2:39

Attachments:
- [start.sh](https://storage.googleapis.com/google-code-attachments/terrastore/issue-23/comment-10/start.sh)

**Comment by GoogleCodeExporter** [comment]
```
Configuration needs to be loaded from the master, but it seems to be unable to 
properly resolve the 
address localhost:9510 probably because the colon is wrongly escaped ... you 
should try to avoid that 
bad escaping ... 

```

Original comment by `sergio.b...@gmail.com` on 2 Jan 2010 at 3:18

**Comment by GoogleCodeExporter** [comment]
```
I'm still away from my computer, I'll give a look at it later ...
```

Original comment by `sergio.b...@gmail.com` on 2 Jan 2010 at 5:25

**Comment by GoogleCodeExporter** [comment]
```
I can connect the master (cygwin) from a server running on nbuntu. Connecting 
with a
server on cygwin is still a problem :-(
I think I tried it all (ascaping, quote's, adding the parameter in the script. 
Always
the same result that it seems it doens't connect to the master
```

Original comment by `mark.wig...@gmail.com` on 2 Jan 2010 at 6:39

**Comment by GoogleCodeExporter** [comment]
```
Mark, I'll definitely debug your script on cygwin tomorrow.
Sorry for this taking so long.

Cheers,

Sergio B.
```

Original comment by `sergio.b...@gmail.com` on 4 Jan 2010 at 7:30

**Comment by GoogleCodeExporter** [comment]
```
Mark,

Now everything should work on cygwin.
Please checkout (or update) sources, build a terrastore package with "mvn clean
package assembly:assembly" and reinstall both master and server.

Let me know.
Cheers,

Sergio B.
```

Original comment by `sergio.b...@gmail.com` on 5 Jan 2010 at 11:17

**Comment by GoogleCodeExporter** [comment]
Original comment by `sergio.b...@gmail.com` on 6 Jan 2010 at 3:59
- Changed title: **Cygwin problem in startup scripts**
- Added labels: **Priority-Medium**, **Milestone-0.3.1**

**Comment by GoogleCodeExporter** [comment]
```
Resolved in 0.3.1.
```

Original comment by `sergio.b...@gmail.com` on 7 Jan 2010 at 10:09
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
hey guys has anyone tried this on unix
```

Original comment by `rj.nara...@gmail.com` on 27 May 2010 at 2:38

**Comment by GoogleCodeExporter** [comment]
```
Hi,

what kind of problems are you experiencing?
What operating system are you using?
```

Original comment by `sergio.b...@gmail.com` on 27 May 2010 at 2:41
