### ISSUE TITLE
Bad version number in .class file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [byzhang/terrastore#44]
```
I get the following error when trying to start the server (after a successful 
master startup) on my 
MacBook Pro: 

MacBook-Pro:bin gislik$ sh start.sh --master localhost:9510
Starting Terrastore Server ...
Exception in thread "main" java.lang.UnsupportedClassVersionError: Bad version 
number in .class 
file
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:676)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:56)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
        at sun.misc.Launcher$AppClassLoader.findClass(Launcher.java)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:317)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:280)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
        at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:375)

My JDK is:

MacBook-Pro:bin gislik$ java -version
java version "1.5.0_22"
Java(TM) 2 Runtime Environment, Standard Edition (build 1.5.0_22-b03-333-9M3125)
Java HotSpot(TM) Client VM (build 1.5.0_22-147, mixed mode, sharing)
```

Original issue reported on code.google.com by `mr.krist...@gmail.com` on 5 Apr 2010 at 5:03

**Comment by GoogleCodeExporter** [comment]
```
Both Terrastore master and server require java 1.6.
Please try with that and let me know.
```

Original comment by `sergio.b...@gmail.com` on 5 Apr 2010 at 5:13
- Changed state: **Accepted**
- Added labels: **Type-Defect**, **Project-Terrastore**

**Comment by GoogleCodeExporter** [comment]
```
Not a Terrastore issue.
```

Original comment by `sergio.b...@gmail.com` on 17 Apr 2010 at 10:43
- Changed state: **Invalid**
