### ISSUE TITLE
Java Client doesn't send update execution when no parameters are set

### ISSUE THREAD

**Issue by GoogleCodeExporter** [byzhang/terrastore#67]
```
The Java Client should support execution of update function with no parameters.
Currently, when no parameters are provided the client crashes.
```

Original issue reported on code.google.com by `sergio.b...@gmail.com` on 21 Jun 2010 at 8:55
- Blocked on: #71

**Comment by GoogleCodeExporter** [comment]
```
Unable to perform update
terrastore.client.connection.TerrastoreConnectionException: Unable to perform 
update
        at terrastore.client.connection.resteasy.HTTPConnection.connectionException(HTTPConnection.java:353)
        at terrastore.client.connection.resteasy.HTTPConnection.executeUpdate(HTTPConnection.java:336)
        at terrastore.client.UpdateOperation.executeAndGet(UpdateOperation.java:89)
        at terrastore.client.test.integration.TerrastoreClientIntegrationTest.testExecuteUpdateWithNoParameters(TerrastoreClientIntegrationTest.java:349)
Caused by: java.lang.NullPointerException
        at org.jboss.resteasy.client.ClientRequest.body(ClientRequest.java:304)
        at terrastore.client.connection.resteasy.HTTPConnection.executeUpdate(HTTPConnection.java:327)
```

Original comment by `sergio.b...@gmail.com` on 21 Jun 2010 at 8:57

**Comment by GoogleCodeExporter** [comment]
```
Available workaround: just send an empty map.
```

Original comment by `sergio.b...@gmail.com` on 21 Jun 2010 at 8:59

**Comment by GoogleCodeExporter** [comment]
```
Attaching a diff file containing the failing test showing this issue.
```

Original comment by `sergio.b...@gmail.com` on 21 Jun 2010 at 9:03

Attachments:
- [TerrastoreClientIntegrationTest.java.diff](https://storage.googleapis.com/google-code-attachments/terrastore/issue-67/comment-3/TerrastoreClientIntegrationTest.java.diff)

**Comment by GoogleCodeExporter** [comment]
Original comment by `sergio.b...@gmail.com` on 21 Jun 2010 at 9:03

**Comment by GoogleCodeExporter** [comment]
```
Sven,

any news about this issue?
```

Original comment by `sergio.b...@gmail.com` on 28 Jun 2010 at 10:20

**Comment by GoogleCodeExporter** [comment]
```
Sven,

I've just pushed the fix, see.
Please verify issue 71 isn't a blocker.
```

Original comment by `sergio.b...@gmail.com` on 28 Jun 2010 at 3:31
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Fixed.
```

Original comment by `sergio.b...@gmail.com` on 24 Jul 2010 at 10:43

**Comment by GoogleCodeExporter** [comment]
Original comment by `sergio.b...@gmail.com` on 24 Jul 2010 at 10:43
- Changed state: **Fixed**
