### ISSUE TITLE
The server should not log a stack trace for key not found

### ISSUE THREAD

**Issue by GoogleCodeExporter** [byzhang/terrastore#69]
```
If you search for a an object with a non-existing key, the server will dump a 
pretty nasty-looking stack trace to the log/console (see below). My suggestion 
is to log a warning entry instead (without the stack trace) which would log 
bucket and key name.

While we're at it, I think we should make sure operations on non-existing 
buckets should be handled the same way.


Terrastore Server 0.5.1 - 00:22:40.995 - Key not found: plato
terrastore.service.QueryOperationException: Key not found: plato
    at terrastore.service.impl.DefaultQueryService.getValue(DefaultQueryService.java:96) [terrastore-0.5.1.jar:na]
    at terrastore.server.impl.JsonHttpServer.getValue(JsonHttpServer.java:148) [terrastore-0.5.1.jar:na]
    at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) [na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [na:1.6.0_16]
    at java.lang.reflect.Method.invoke(Method.java:597) [na:1.6.0_16]
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:124) [resteasy-jaxrs-1.2.GA.jar:na]
    at org.jboss.resteasy.core.ResourceMethod.invokeOnTarget(ResourceMethod.java:247) [resteasy-jaxrs-1.2.GA.jar:na]
    at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:212) [resteasy-jaxrs-1.2.GA.jar:na]
    at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:202) [resteasy-jaxrs-1.2.GA.jar:na]
    at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:441) [resteasy-jaxrs-1.2.GA.jar:na]
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:418) [resteasy-jaxrs-1.2.GA.jar:na]
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:111) [resteasy-jaxrs-1.2.GA.jar:na]
    at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:206) [resteasy-jaxrs-1.2.GA.jar:na]
    at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:159) [resteasy-jaxrs-1.2.GA.jar:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820) [servlet-api-2.5-20081211.jar:na]
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) [jetty-6.1.22.jar:6.1.22]
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390) [jetty-6.1.22.jar:6.1.22]
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765) [jetty-6.1.22.jar:6.1.22]
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) [jetty-6.1.22.jar:6.1.22]
    at org.mortbay.jetty.Server.handle(Server.java:326) [jetty-6.1.22.jar:6.1.22]
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) [jetty-6.1.22.jar:6.1.22]
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923) [jetty-6.1.22.jar:6.1.22]
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547) [jetty-6.1.22.jar:6.1.22]
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212) [jetty-6.1.22.jar:6.1.22]
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) [jetty-6.1.22.jar:6.1.22]
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409) [jetty-6.1.22.jar:6.1.22]
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582) [jetty-util-6.1.22.jar:6.1.22]

```

Original issue reported on code.google.com by `mats.hen...@gmail.com` on 25 Jun 2010 at 1:55

**Comment by GoogleCodeExporter** [comment]
Original comment by `sergio.b...@gmail.com` on 25 Jun 2010 at 2:04
- Changed state: **Accepted**
- Added labels: **Type-Enhancement**, **Priority-Low**, **Project-Terrastore**, **Milestone-0.5.2**

**Comment by GoogleCodeExporter** [comment]
```
All user-related invalid operations (such as looking for a missing key) don't 
log any stack trace anymore, only server-related errors log full traces.

To enable full logging for all kind of errors, just configure the logging level 
to INFO.
```

Original comment by `sergio.b...@gmail.com` on 4 Jul 2010 at 10:09
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `sergio.b...@gmail.com` on 18 Jul 2010 at 4:39
- Added labels: **Milestone-0.6.0**

**Comment by GoogleCodeExporter** [comment]
Original comment by `sergio.b...@gmail.com` on 24 Jul 2010 at 10:45
- Removed labels: **Milestone-0.5.2**
